### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by chasecrampton** [TheShadowGamer/Password-System#2]
- [x] Add an eye button to show/hide password
- [x] Ability to lock servers
- [x] Hotkey to lock discord
- [x] Add option to redirect to a specific url if password is incorrect

**Comment by TheShadowGamer** [comment]
So, I cannot seem to figure out the part about adding an eye button. I can figure out the JavaScript for it, but not how to add the button. If I don't figure it out in a few days, I think I will just push everything else and leave the eye button for later.

**Comment by chasecrampton** [comment]
ok np

**Comment by TheShadowGamer** [comment]
> Add an eye button to show/hide password

Expect this soon. I got that to work with some help from someone. Keeping everything secret for now.

**Comment by TheShadowGamer** [comment]
@Chromus-dev #5 👀
