### ISSUE TITLE
🐛 Input Fix

### ISSUE THREAD

**Issue by chasecrampton** [TheShadowGamer/Password-System#4]
When you hit "Enter" in the password input, it makes a new line instead of entering that as the password.
Ex: https://i.imgur.com/BcrjM22.gif

**Comment by TheShadowGamer** [comment]
Alright. I’ll look into this tomorrow.

**Comment by chasecrampton** [comment]
One last feature you could add:
Make the password blurred hen typing it unless you hover on it or something like that. That would include where you set the password.

**Comment by TheShadowGamer** [comment]
> One last feature you could add:
> Make the password blurred hen typing it unless you hover on it or something like that. That would include where you set the password.

@Chromus-dev That kind of goes off of the thing you suggested in #2. Idk I'll look into it, but no guarantees.

**Comment by TheShadowGamer** [comment]
Complete in the newest version @Chromus-dev
